### PR TITLE
Rewrite of preload cds function in data service

### PR DESCRIPTION
**Pull request by c-h-russell-walker**
@pbouzakis - I've set this up as its own pull request in response to your comment here:

https://github.com/c-h-russell-walker/manage-cds/commit/e88cfc4b2d4c6b238803ee0c7b476d1840f5214a#commitcomment-8865523

I wasn't sure if this was how you envisioned the update and also I needed to manually trigger the observable update which seemed incorrect.

Would love to know why that's the case and any other feedback - thanks!

### CODE REVIEW

**Comment by pbouzakis** [comment]
:+1: 

Why do we need the `valueHasMutated` method? With KO, we know something has mutated when you set (you can subscribe to observable changes).

**Comment by c-h-russell-walker** [comment]
I'm not sure why I have to trigger the update manually - but I tested in both Chrome and FF and it doesn't update unless i trigger the `valueHasMutated`.

Happy to update but unsure what is the best approach.

Thanks!

**Comment by c-h-russell-walker** [comment]
Closing because it's _very_ _very_ stale 😎

**Comment by c-h-russell-walker** [comment]
Closing because it's _very_ _very_ stale 😎

**Pull request closed without merging**
